# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Builds A2UI envelopes: the JSON payload a FunctionTool hands back to the
client describing a surface (createSurface), the component tree that fills
it (updateComponents), and any bound data (updateDataModel).

Deliberately NOT generated by the LLM. The reference A2UI SDKs teach a model
to hand-author this JSON in free text and then parse/heal/validate whatever
comes out. GEAP agents build it with plain, deterministic Python instead --
:class:`SurfaceBuilder` -- and only let the model choose numbers and copy via
normal, schema-checked function-call arguments. See docs/A2UI.md for the
reasoning: it trades a small amount of the reference SDK's flexibility for
JSON that is *always* well-formed and catalog-valid, no LLM JSON-healing
required.
"""

from __future__ import annotations

from app.a2ui.catalog import CATALOG_ID, CATALOG_VERSION, COMPONENT_TYPES


class SurfaceBuilder:
    """Incrementally assembles one A2UI surface envelope.

    Usage::

        b = SurfaceBuilder("retirement-dashboard", title="Planning & Retirement")
        b.add("hero", "hero_cta", {...})
        b.add("stats", "stat_grid")
        b.add("stat-age", "stat_tile", {...}, parent="stats")
        b.set_data(generatedAt=..., agent="planning_agent")
        envelope = b.build()
    """

    def __init__(self, surface_id: str, title: str, subtitle: str = ""):
        self.surface_id = surface_id
        self._components: dict[str, dict] = {}
        self._data_model: dict = {}
        self._add_component("root", "surface", {"title": title, "subtitle": subtitle})

    def _add_component(
        self,
        component_id: str,
        component_type: str,
        props: dict | None = None,
    ) -> None:
        if component_type not in COMPONENT_TYPES:
            known = ", ".join(sorted(COMPONENT_TYPES))
            raise ValueError(
                f"Unknown A2UI component type {component_type!r}. Known types: {known}"
            )
        if component_id in self._components:
            raise ValueError(f"Duplicate component id {component_id!r}")
        self._components[component_id] = {
            "id": component_id,
            "type": component_type,
            "props": props or {},
            "children": [],
        }

    def add(
        self,
        component_id: str,
        component_type: str,
        props: dict | None = None,
        *,
        parent: str = "root",
    ) -> str:
        """Add a component and attach it as a child of ``parent`` (default: root).

        Returns ``component_id`` so calls can be chained inline.
        """
        self._add_component(component_id, component_type, props)
        if parent not in self._components:
            raise ValueError(f"Unknown parent component id {parent!r}")
        self._components[parent]["children"].append(component_id)
        return component_id

    def set_data(self, **fields) -> None:
        """Merge fields into this surface's bound data model."""
        self._data_model.update(fields)

    def build(self) -> dict:
        """Return the full envelope: createSurface + updateComponents + updateDataModel."""
        return {
            "version": CATALOG_VERSION,
            "catalogId": CATALOG_ID,
            "messages": [
                {
                    "type": "createSurface",
                    "surfaceId": self.surface_id,
                    "root": "root",
                },
                {
                    "type": "updateComponents",
                    "surfaceId": self.surface_id,
                    "components": list(self._components.values()),
                },
                {
                    "type": "updateDataModel",
                    "surfaceId": self.surface_id,
                    "data": dict(self._data_model),
                },
            ],
        }
